"""Spending frequency analyzer (façade over :mod:`ledgerlogic.analysis`)."""

from __future__ import annotations

from .analysis import (
    DAY_NAMES,
    coerce_analysis_records,
    count_by_merchant,
    day_of_week_breakdown,
    detect_anomalies,
    detect_columns,
    generate_mock_transactions,
    group_category_averages,
    load_categorized_file,
    main,
    menu,
    month_start_from_offset,
    monthly_trends,
    normalize_analysis_record,
    print_anomalies,
    print_day_breakdown,
    print_full_analysis,
    print_monthly_trends,
    print_top_frequency,
    print_top_spend,
    rule_payload_from_merchant,
    run_all_reports,
    spend_by_merchant,
    time_of_month_analysis,
    weekend_vs_weekday,
)

__all__ = [
    "DAY_NAMES",
    "coerce_analysis_records",
    "normalize_analysis_record",
    "count_by_merchant",
    "day_of_week_breakdown",
    "detect_anomalies",
    "detect_columns",
    "generate_mock_transactions",
    "group_category_averages",
    "load_categorized_file",
    "main",
    "menu",
    "month_start_from_offset",
    "monthly_trends",
    "print_anomalies",
    "print_day_breakdown",
    "print_full_analysis",
    "print_monthly_trends",
    "print_top_frequency",
    "print_top_spend",
    "rule_payload_from_merchant",
    "run_all_reports",
    "spend_by_merchant",
    "time_of_month_analysis",
    "weekend_vs_weekday",
]
